# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: /
    weight: 10
  - name: Publications
    url: publications/
    weight: 13
  - name: Professional Activities
    url: service-outreach/
    weight: 15
  - name: Beyond the Lab
    url: beyond-the-lab/
    weight: 40
  - name: Education & Awards
    url: experience/
    weight: 11
  - name: Research
    url: research/
    weight: 12
  - name: Teaching
    url: teaching/
    weight: 14 #40
